export const eighthFormData = [
  {
    id: 'description1',
    name: 'description',
    label: 'Kopftuch',
    value: 'Kopftuch',
    checked: false,
  },
  {
    id: 'description2',
    name: 'description',
    label: 'Abaya',
    value: 'Abaya',
    checked: false,
  },
  {
    id: 'description3',
    name: 'description',
    label: 'Turban',
    value: 'Turban',
    checked: false,
  },
  {
    id: 'description4',
    name: 'description',
    label: 'Bart',
    value: 'Bart',
    checked: false,
  },
  {
    id: 'description5',
    name: 'description',
    label: 'Hautfarbe',
    value: 'Hautfarbe',
    checked: false,
  },
  {
    id: 'description6',
    name: 'description',
    label: 'Haare',
    value: 'Haare',
    checked: false,
  },
  {
    id: 'description7',
    name: 'description',
    label: 'Augen',
    value: 'Augen',
    checked: false,
  },
  {
    id: 'description8',
    name: 'description',
    label: 'Sprache',
    value: 'Sprache',
    checked: false,
  },
  {
    id: 'description9',
    name: 'description',
    label: '„Nichtdeutscher“ Name',
    value: '„Nichtdeutscher“ Name',
    checked: false,
  },
  {
    id: 'description10',
    name: 'description',
    label: 'Religiöse Ausübung (z.B Beten oder fasten)',
    value: 'Religiöse Ausübung (z.B Beten oder fasten)',
    checked: false,
  },
  {
    id: 'description11',
    name: 'description',
    label: 'Kleidung',
    value: 'Kleidung',
    checked: false,
  },
  {
    id: 'description12',
    name: 'description',
    label: 'Anderes, und zwar:',
    value: 'Anderes, und zwar:',
    checked: false,
  },
];
